import {
    pgTable,
    uuid,
    text,
    boolean,
    timestamp,
    date,
    index,
    uniqueIndex,
} from 'drizzle-orm/pg-core';
import { users } from './users.schema.js';
import { departments } from './departments.schema.js';
import { jobPositions } from './job_positions.schema.js';
import { workingSchedules } from './working_schedules.schema.js';
import { employeeStatusEnum } from './enums.schema.js';

/**
 * employees
 *
 * Central hub of the entire PeoplePay360 system.
 * Almost every other table (contracts, attendance, payslips, time off)
 * references this table via employee_id.
 *
 * Design notes:
 *   - user_id (1:1) links the HR record to the auth user. An employee MUST have a
 *     user account for portal login. RESTRICT on delete — never silently orphan.
 *   - manager_id is self-referencing (nullable = top of hierarchy).
 *   - hire_date is DATE (calendar concept, no time/timezone needed).
 *   - working_schedule_id is nullable — some employees may not have a schedule yet.
 *   - is_active soft-delete guards payroll history; never hard-delete employees
 *     that have payslips, contracts, or attendance records.
 */
export const employees = pgTable(
    'employees',
    {
        id: uuid('id').defaultRandom().primaryKey(),

        // 1:1 link to the auth users table.
        // RESTRICT: cannot delete a user who is an employee.
        userId: uuid('user_id')
            .references(() => users.id, { onDelete: 'restrict' })
            .unique(),

        // Human-readable employee identifier (e.g. 'EMP-001').
        // Generated by the service; unique across the org.
        employeeCode: text('employee_code').unique().notNull(),

        // Personal info — denormalised from users for HR display independence.
        firstName: text('first_name').notNull(),
        lastName: text('last_name').notNull(),
        email: text('email').notNull(),
        phone: text('phone'),
        gender: text('gender'),
        dateOfBirth: date('date_of_birth'),
        address: text('address'),

        // Employment dates.
        // DATE type — calendar concept, not a timestamped event.
        hireDate: date('hire_date').notNull(),
        terminationDate: date('termination_date'),

        // Organisational context.
        // SET NULL: dept or position can be deleted without cascading to employee.
        departmentId: uuid('department_id').references(() => departments.id, {
            onDelete: 'set null',
        }),
        jobPositionId: uuid('job_position_id').references(() => jobPositions.id, {
            onDelete: 'set null',
        }),

        // Self-referencing manager hierarchy (nullable = no manager / CEO).
        // SET NULL: if a manager is archived, their reports become top-level.
        managerId: uuid('manager_id'),
        // NOTE: FK managed separately: ALTER TABLE employees ADD CONSTRAINT ...
        // REFERENCES employees(id) ON DELETE SET NULL — avoids Drizzle circular ref.

        // Assigned working schedule (nullable — assigned post-onboarding).
        workingScheduleId: uuid('working_schedule_id').references(() => workingSchedules.id, {
            onDelete: 'set null',
        }),

        // Lifecycle state machine: DRAFT → ACTIVE → SUSPENDED | ARCHIVED
        status: employeeStatusEnum('status').default('DRAFT').notNull(),

        // Soft-delete flag. Archived employees keep all historical data intact.
        isActive: boolean('is_active').default(true).notNull(),

        notes: text('notes'),

        // Audit: who created this employee record.
        createdBy: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),

        createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
        updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
    },
    (table) => ({
        // Unique index on user_id enforces the 1:1 employees ↔ users relationship.
        userIdIdx: uniqueIndex('employees_user_id_idx').on(table.userId),

        // Composite index for HR list views filtered by dept + status.
        deptStatusIdx: index('employees_dept_status_idx').on(table.departmentId, table.status),

        // Index for payroll queries: "get all active employees".
        statusIdx: index('employees_status_idx').on(table.status),
        isActiveIdx: index('employees_is_active_idx').on(table.isActive),

        // Index for manager hierarchy lookups.
        managerIdIdx: index('employees_manager_id_idx').on(table.managerId),
    }),
);
